[package]
name = "venus-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
log = "0.4.22"
thiserror = "1.0.61"
toml = "0.8.14"
serde = { version = "1.0.203", features = ["derive", "serde_derive"] }
serde_json = { version = "1.0.120" }
